defaults:
  - _self_
  - dataset: "zebrafish"

pc_dim: -1
num_classes: -1

seed: 42

# Trainer settings
classifier_max_epochs: 1000
metric_max_epochs: 3000
embed_max_epochs: 3000
flow_max_epochs: 2
gradient_clip_val: 0
warmup_steps: 0

loader_batch_size: 6
flow_batch_size: 512
score_batch_size: 2048
ema_decay: 1-1e-3

use_paga: False

# Model Hparams
lr: 1e-3
dropout: 0.0
hidden_dim: 256
latent_dim: 100
num_layers: 3
num_freq: 32

rescale: 0.5
skip: False
normalize: True
balance_classes: False

# Debug settings
force_cpu: False
detect_anomaly: False
use_wandb: True

# Classifier settings
dummy_prior: 0.05
dummy_kl_weight: 0.05

classifier:
  hidden_dim: 20
  num_layers: 1
  spectral_norm: False
  epsilon: 0.0

# Metric / Flow settings
metric: "cfm"
sigma: 0.0
ot_in_embed: True
fast_ot: False
no_learning: False
time_per_batch: 4
random_velocities: False

method: "exact"
reg: -1
reg_m: -1

mfm:
  K: 150
  kappa: 1.5
  alpha: 1.0
  epsilon: 1e-1
  use_euclidean_ot: False

finsler:
  use: False
  temp: 1.0
  lamb: 1.0
