method: grid

metric:
  name: w1_avg
  goal: minimize

parameters:
  metric:
    values: ["sbcfm"]
  finsler.use:
    values: [true]
  finsler.lamb:
    values: [0.5, 1.0]
  sigma:
    values: [0.1, 0.25]
  classifier.hidden_dim:
    values: [128]
  classifier.num_layers:
    values: [2]
  classifier.epsilon:
    values: [0.05]
  use_euclidean_ot:
    values: [true, false]
  seed:
    values: [1, 2, 3, 4, 5]
